### ISSUE TITLE
Issue when running git-bpf-init  on windows 10

### ISSUE THREAD

**Issue by habax** [affinitybridge/git-bpf#14]
I'm getting the next error when i run "git-bpf-init" in windows 10:

fatal: No such section!
C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/git-helpers.rb:16:in ``': No such file or directory - /usr/bin/tput cols (Errno::ENOENT)
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/git-helpers.rb:16:in`width'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/git-helpers.rb:36:in `ohai'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/commands/init.rb:94:in`execute'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/gitflow.rb:197:in `block in run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/gitflow.rb:183:in`catch'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/lib/git_bpf/lib/gitflow.rb:183:in `run'
        from C:/Ruby22/lib/ruby/gems/2.2.0/gems/git_bpf-1.0.1/bin/git-bpf-init:6:in`block in <top (required)>'

can anybody help me ?

**Comment by habax** [comment]
After try a lot of things I discovered one solution  to run git-bpf-init:
1. First we need a console(64 bits) with a basic unix commands.

Install a [git 2.x ](https://git-for-windows.github.io/) or newest (this installation include a console called mingw64 ). In the installation wizard select the option (step: Adjusting your path environment) "use git and optinoal unix tools from the windows command promt", and then (step: configuring the terminal emulator to use with git bash) select the option: "Use MinTTY (the dafault terminal of MSYS2)"
Or Download this: [mingw-w64](https://sourceforge.net/projects/mingw-w64/?source=typ_redirect)

When the installation has finished open a "git bash" terminal
1. Try "git-bpf-init" with the mingw64 console,  if you can run this command and all it's ok, we finish here.

But if you see the next error: [symlink() function is unimplemented on this machine](https://github.com/affinitybridge/git-bpf/issues/12) be sure to follow the step 2.1 

2.1 we need to compile a [gem indicated on the forum](https://github.com/affinitybridge/git-bpf/issues/12) (by @hazzik ). In order to do that, we need to have installed two ruby gems ( [bundle](http://bundler.io/) and [rake](https://github.com/ruby/rake))

```
    2.1.1 Clone the Git repository.
     $ git clone https://github.com/hazzik/git-bpf.git
2.1.2 Change to the new directory.
     $ cd git-bpf   
2.1.3 Install bundles
     $ bundle install
2.1.4 Build the gem.
     $ rake build
2.1.6 Install the gem.
     $ gem install pkg/git_bpf-1.0.1.gem
```

After that, the gem from the repository was intalled. Try again "git-bpf-init" in your project repository, and now it's running
